#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';

const VERSION='1.0.0';
const IGNORE=new Set(['.git','node_modules','agent','core','commands','platforms','knowledge','scripts','tools','docs','templates','.github','.claude','.cursor','.agents','.opencode','.pangea-backup']);
const LEGACY_PATTERN=/(Web\s*Architect\s*OS|_web-os|web-architect)/i;
function out(x){console.log(typeof x==='string'?x:JSON.stringify(x,null,2));}
function die(x){console.error(`PANGEA ERROR: ${x}`);process.exit(1);}
function read(p){try{return JSON.parse(fs.readFileSync(p,'utf8'));}catch(e){die(`Cannot read ${p}: ${e.message}`);}}
function write(p,o){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(o,null,2)+'\n');}
function git(root,args,f=null){try{return execFileSync('git',args,{cwd:root,encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim();}catch{return f;}}
function gitState(root){const ok=git(root,['rev-parse','--is-inside-work-tree'],'false')==='true';if(!ok)return{is_git:false,branch:null,commit:null,working_tree:'UNKNOWN',upstream:null,ahead:null,behind:null};const branch=git(root,['branch','--show-current'],null),commit=git(root,['rev-parse','HEAD'],null),working_tree=git(root,['status','--porcelain'],'')?'DIRTY':'CLEAN',upstream=git(root,['rev-parse','--abbrev-ref','--symbolic-full-name','@{upstream}'],null);let ahead=null,behind=null;if(upstream){const raw=git(root,['rev-list','--left-right','--count',`${upstream}...HEAD`],null);if(raw){const [b,a]=raw.split(/\s+/).map(Number);behind=b;ahead=a;}}return{is_git:true,branch,commit,working_tree,upstream,ahead,behind};}
function has(dir,f){return fs.existsSync(path.join(dir,f));}
function safeText(file){try{const s=fs.statSync(file);if(!s.isFile()||s.size>1024*1024)return'';return fs.readFileSync(file,'utf8');}catch{return'';}}
function dirContainsLegacy(dir,depth=0){if(depth>3||!fs.existsSync(dir))return false;for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(e.name==='node_modules'||e.name==='.git')continue;const p=path.join(dir,e.name);if(e.isDirectory()){if(dirContainsLegacy(p,depth+1))return true;}else if(LEGACY_PATTERN.test(safeText(p)))return true;}return false;}
function legacyArtifacts(dir){const found=[];const checks=[['_web-os','legacy-engine-directory'],['AGENTS.md','nested-agent-entry'],['CLAUDE.md','nested-claude-entry'],['opencode.json','nested-opencode-config'],['.opencode','nested-opencode-adapter'],['.cursor','nested-cursor-adapter'],['.claude','nested-claude-adapter'],['.agents','nested-codex-adapter']];for(const [rel,kind] of checks){const p=path.join(dir,rel);if(!fs.existsSync(p))continue;if(rel==='_web-os'||(fs.statSync(p).isDirectory()?dirContainsLegacy(p):LEGACY_PATTERN.test(safeText(p))))found.push({path:rel,kind,severity:'WARN',reason:'Legacy Web Architect OS instructions can conflict with the Pangea root kernel.'});}return found;}
function detect(dir){
 let pkg=null;if(has(dir,'package.json')){try{pkg=read(path.join(dir,'package.json'));}catch{}}
 const deps={...(pkg?.dependencies||{}),...(pkg?.devDependencies||{})};let type='unknown',stack=[];
 if(has(dir,'layout/theme.liquid')||has(dir,'config/settings_schema.json')){type='shopify-theme';stack.push('Shopify Liquid');}
 else if(deps.next){type='nextjs';stack.push('Next.js');}else if(deps.astro){type='astro';stack.push('Astro');}else if(deps['@sveltejs/kit']||deps.svelte){type='svelte';stack.push('Svelte');}else if(deps.nuxt){type='nuxt';stack.push('Nuxt');}else if(deps.vite){type='vite';stack.push('Vite');}else if(has(dir,'wp-config.php')||(has(dir,'style.css')&&has(dir,'functions.php'))){type='wordpress';stack.push('WordPress');}else if(has(dir,'index.html')){type='static';stack.push('Static HTML');}
 if(deps.react)stack.push('React');if(deps.vue)stack.push('Vue');if(deps.typescript||has(dir,'tsconfig.json'))stack.push('TypeScript');if(deps.express)stack.push('Express');if(deps.tailwindcss)stack.push('Tailwind CSS');
 const scripts=pkg?.scripts||{};return{type,stack:[...new Set(stack)],package_name:pkg?.name||null,scripts,markers:['package.json','vite.config.ts','vite.config.js','next.config.js','next.config.mjs','astro.config.mjs','layout/theme.liquid','index.html'].filter(f=>has(dir,f)),legacy_instructions:legacyArtifacts(dir)};
}
function candidates(root){return fs.readdirSync(root,{withFileTypes:true}).filter(e=>e.isDirectory()&&!IGNORE.has(e.name)&&!e.name.startsWith('.')).map(e=>({name:e.name,path:path.join(root,e.name),detected:detect(path.join(root,e.name))})).filter(x=>x.detected.type!=='unknown'||x.detected.markers.length||x.detected.legacy_instructions.length);}
function slug(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function ahpVerify(root){try{return JSON.parse(execFileSync(process.execPath,[path.join(root,'tools/ahp-plus/ahp.mjs'),'verify',root],{encoding:'utf8'}));}catch(e){try{return JSON.parse(e.stdout?.toString()||'{}');}catch{return{ok:false,error:e.message};}}}
function rootWarnings(root,found=candidates(root)){const warnings=[];if(has(root,'_web-os'))warnings.push({code:'LEGACY_ROOT_ENGINE',path:'_web-os',message:'Legacy root _web-os remains present. Keep it only as archived source or migrate it after review.'});for(const c of found)for(const item of c.detected.legacy_instructions)warnings.push({code:'NESTED_LEGACY_INSTRUCTIONS',project:slug(c.name),path:path.join(c.name,item.path),message:item.reason});return warnings;}
function doctor(root){const required=['AGENTS.md','core/00_CONSTITUTION.md','agent/MANIFEST.json','tools/ahp-plus/ahp.mjs'];const missing=required.filter(f=>!has(root,f));const ahp=missing.length?{ok:false,error:'required files missing'}:ahpVerify(root);const found=candidates(root),warnings=rootWarnings(root,found);const result={pangea:VERSION,root,git:gitState(root),required:{ok:missing.length===0,missing},ahp,projects_detected:found.length,warnings,alive:missing.length===0&&ahp.ok};out(result);if(!result.alive)process.exit(2);}
function mergeManual(existing,observed){const keep=['invariants','source_of_truth','design_direction','known_risks','notes','owner','commercialization'];const merged={...observed};for(const k of keep)if(existing?.[k]!==undefined)merged[k]=existing[k];return merged;}
function scan(root){const regPath=path.join(root,'agent/PROJECTS.json');const reg=has(root,'agent/PROJECTS.json')?read(regPath):{schema_version:'1.0.0',projects:[]};const found=candidates(root),rootGit=gitState(root);for(const c of found){const id=slug(c.name),rel=path.relative(root,c.path)||'.',existing=reg.projects.find(x=>x.project_id===id);const observed={project_id:id,name:c.name,path:rel,status:c.detected.legacy_instructions.length?'NEEDS_MIGRATION_REVIEW':'REGISTERED',detected:c.detected,git:has(c.path,'.git')?gitState(c.path):{managed_by_root_git:rootGit.is_git,root_branch:rootGit.branch,root_commit:rootGit.commit},observed_at:new Date().toISOString(),confidence:'VERIFIED'};const profile=mergeManual(existing,observed);if(existing)Object.assign(existing,profile);else reg.projects.push(profile);const dir=path.join(root,'agent/projects',id);fs.mkdirSync(dir,{recursive:true});write(path.join(dir,'profile.json'),profile);const legacy=c.detected.legacy_instructions.length?['','## Migration warnings',...c.detected.legacy_instructions.map(x=>`- \`${x.path}\`: ${x.reason}`)]:[];fs.writeFileSync(path.join(dir,'PROJECT.md'),[`# ${c.name}`,'',`- Project ID: ${id}`,`- Path: \`${rel}\``,`- Type: ${c.detected.type}`,`- Stack: ${c.detected.stack.join(', ')||'Unknown'}`,`- Confidence: VERIFIED by filesystem scan`,'','## Commands',...(Object.entries(c.detected.scripts).map(([k,v])=>`- \`npm run ${k}\`: \`${v}\``).length?Object.entries(c.detected.scripts).map(([k,v])=>`- \`npm run ${k}\`: \`${v}\``):['- No package scripts detected.']),...legacy,''].join('\n'));}
 reg.updated_at=new Date().toISOString();write(regPath,reg);out({registered:found.length,projects:reg.projects,warnings:rootWarnings(root,found)});}
function registry(root){return read(path.join(root,'agent/PROJECTS.json'));}
function selectProject(root,id){const reg=registry(root),p=reg.projects.find(x=>x.project_id===id||slug(x.name)===id);if(!p)die(`project not registered: ${id}. Run scan first.`);const statePath=path.join(root,'agent/CURRENT_STATE.json'),c=read(statePath),gs=gitState(root);c.project_id=p.project_id;c.phase='DISCOVERY';c.objective=`Understand and operate project ${p.name}`;c.base_commit=gs.commit;c.working_tree=gs.working_tree;c.next_action=`Run /pangea bootstrap ${p.project_id} or inspect agent/projects/${p.project_id}/PROJECT.md`;c.updated_at=new Date().toISOString();c.confidence='VERIFIED';c.blockers=p.detected?.legacy_instructions?.length?['Review nested legacy agent instructions before editing.']:[];write(statePath,c);out({selected:p,current:c});}
function project(root,id){const p=registry(root).projects.find(x=>x.project_id===id||slug(x.name)===id);if(!p)die(`project not registered: ${id}`);out(p);}
function conflicts(root){const found=candidates(root);out({count:rootWarnings(root,found).length,warnings:rootWarnings(root,found)});}
function status(root){const reg=registry(root),cur=read(path.join(root,'agent/CURRENT_STATE.json')),selected=reg.projects.find(p=>p.project_id===cur.project_id)||null,warnings=rootWarnings(root);out({pangea:VERSION,alive:true,git:gitState(root),current:cur,selected_project:selected,projects:reg.projects.map(p=>({project_id:p.project_id,path:p.path,type:p.detected?.type,status:p.status,legacy_conflicts:p.detected?.legacy_instructions?.length||0})),warnings});}
function syncStatus(root){const s=gitState(root);out({...s,note:'This command does not fetch remote refs. Run git fetch only with explicit authorization, then check again.'});}
function usage(){out(`Pangea OS ${VERSION}\nCommands:\n  doctor\n  scan [root]\n  status\n  select <project-id>\n  project <project-id>\n  conflicts\n  sync-status\n  version\n\nSemantic agent commands such as /pangea bootstrap, audit, build and qa are defined in commands/ and require an AI coding host.`);}
const root=path.resolve('.'),cmd=process.argv[2]||'help';if(cmd==='doctor')doctor(root);else if(cmd==='scan')scan(path.resolve(process.argv[3]||'.'));else if(cmd==='status')status(root);else if(cmd==='select')selectProject(root,process.argv[3]||die('project id required'));else if(cmd==='project')project(root,process.argv[3]||die('project id required'));else if(cmd==='conflicts')conflicts(root);else if(cmd==='sync-status')syncStatus(root);else if(cmd==='version')out(VERSION);else usage();
